// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myapp.Data;

#nullable disable

namespace myapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250516020348_planJsonIgnore")]
    partial class planJsonIgnore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("myapp.auth.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Remove Add & Unlock All Location",
                            Icon = "1",
                            Name = "Get Basic"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Remove Add & Unlock All Location",
                            Icon = "crown",
                            Name = "Get Premium"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Remove Add & Unlock All Location",
                            Icon = "2",
                            Name = "Get Basic"
                        });
                });

            modelBuilder.Entity("myapp.auth.Models.PlanFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Limited VR Training",
                            PlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Access to Home Scenario",
                            PlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "AI Chatbot Support",
                            PlanId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Home & Factory Scenarios",
                            PlanId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Full VR Training Access",
                            PlanId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Certification",
                            PlanId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Unlimited VR Training",
                            PlanId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "All Scenarios (Home, Factory, Vehicle)",
                            PlanId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "AI Chatbot + Burn Detection",
                            PlanId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Multi-User & Custom Reports",
                            PlanId = 3
                        });
                });

            modelBuilder.Entity("myapp.auth.Models.PlanOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMonths = 1,
                            Label = "1 Month",
                            Note = "that's Basic Plan",
                            PlanId = 1,
                            Price = 0m,
                            PriceUnit = "EGP"
                        },
                        new
                        {
                            Id = 2,
                            DurationMonths = 6,
                            Label = "6 Month",
                            Note = "that's Premium Plan",
                            PlanId = 1,
                            Price = 310m,
                            PriceUnit = "EGP"
                        },
                        new
                        {
                            Id = 3,
                            DurationMonths = 12,
                            Label = "1 Year",
                            Note = "that's Premium Plan",
                            PlanId = 1,
                            Price = 620m,
                            PriceUnit = "EGP"
                        },
                        new
                        {
                            Id = 4,
                            DurationMonths = 1,
                            Label = "1 Month",
                            Note = "that's Basic Plan",
                            PlanId = 2,
                            Price = 0m,
                            PriceUnit = "EGP"
                        },
                        new
                        {
                            Id = 5,
                            DurationMonths = 6,
                            Label = "6 Month",
                            Note = "that's Premium Plan",
                            PlanId = 2,
                            Price = 310m,
                            PriceUnit = "EGP"
                        },
                        new
                        {
                            Id = 6,
                            DurationMonths = 12,
                            Label = "1 Year",
                            Note = "that's Premium Plan",
                            PlanId = 2,
                            Price = 620m,
                            PriceUnit = "EGP"
                        },
                        new
                        {
                            Id = 7,
                            DurationMonths = 1,
                            Label = "1 Month",
                            Note = "that's Basic Plan",
                            PlanId = 3,
                            Price = 0m,
                            PriceUnit = "EGP"
                        },
                        new
                        {
                            Id = 8,
                            DurationMonths = 6,
                            Label = "6 Month",
                            Note = "that's Premium Plan",
                            PlanId = 3,
                            Price = 310m,
                            PriceUnit = "EGP"
                        },
                        new
                        {
                            Id = 9,
                            DurationMonths = 12,
                            Label = "1 Year",
                            Note = "that's Premium Plan",
                            PlanId = 3,
                            Price = 620m,
                            PriceUnit = "EGP"
                        });
                });

            modelBuilder.Entity("myapp.auth.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("myapp.auth.Models.PlanFeature", b =>
                {
                    b.HasOne("myapp.auth.Models.Plan", "Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("myapp.auth.Models.PlanOption", b =>
                {
                    b.HasOne("myapp.auth.Models.Plan", "Plan")
                        .WithMany("Options")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("myapp.auth.Models.Plan", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
